# Generated by Django 3.2.7 on 2021-09-30 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAnalysis2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=500, null=True)),
                ('process', models.URLField(max_length=100, null=True)),
                ('option', models.CharField(choices=[('DESCRIPTION', 'Description'), ('CATEGORY', 'Category'), ('TAG', 'Tag'), ('OBJECT', 'Detect Object'), ('BRAND', 'Detect Popular Brand'), ('FACES', 'Detect Faces'), ('ADULT', 'Detect Adult, Racy, or Gory Content'), ('COLOR', 'Color Schemes in Images'), ('CELEBRITIES', 'Detect Celebrities'), ('LANDMARK', 'Detect Landmarks'), ('TYPE', 'Detect Image Type')], default='DESCRIPTION', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Key_Endpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(max_length=100, null=True)),
                ('key', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OCR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=500, null=True)),
            ],
        ),
    ]
