FROM golang:alpine as build-env

ENV GO111MODULE=on

RUN apk update && apk add bash ca-certificates git gcc g++ libc-dev

RUN mkdir /grpc_chatapp
RUN mkdir -p /grpc_chatapp/proto 

WORKDIR /grpc_chatapp

COPY ./proto/service.pb.go /grpc_chatapp/proto
COPY ./main.go /grpc_chatapp

COPY go.mod .
COPY go.sum .

RUN go mod download

RUN go build -o grpc_chatapp .

CMD ./grpc_chatapp
